### ISSUE TITLE
How to set `allow-multiline = false` in vscode

### ISSUE THREAD

**Issue by stevenlis** [astral-sh/ruff-vscode#255]
https://github.com/astral-sh/ruff-vscode/issues/253

**Comment by charliermarsh** [comment]
I'd recommend creating a `pyproject.toml` file in the project that you're working on. It would look like this:

```toml
[tool.ruff]
extend-select = ["ISC"]

[tool.ruff.flake8-implicit-str-concat]
allow-multiline = false
```

If you add this to the directory that you're working on, it should be picked up by Ruff without changing any VS Code settings.
