### ISSUE TITLE
Ruff linting internal VSCode files for some reason

### ISSUE THREAD

**Issue by zehkira** [astral-sh/ruff-vscode#261]
![Screenshot](https://github.com/astral-sh/ruff-vscode/assets/111002801/0088e79d-9fed-48e3-b004-f0e537745b28)

This happens once in a while with no clear trigger. Opening and closing any of the files (by clicking on the warnings) fixes it.

I only have one Git repository open, `~/workspace/monophony/`:

![Repositories](https://github.com/astral-sh/ruff-vscode/assets/111002801/b36dea42-d231-45be-9ef4-2f2432d14edf)

Not sure if relevant, but my home directory is also a git repository.

The only modified ruff-vscode setting:

![Ruff extension settings](https://github.com/astral-sh/ruff-vscode/assets/111002801/a84eb6f8-7764-4cbc-b50f-cbe3283bf9ae)

`pyproject.toml`:
```toml
[tool.ruff]
builtins = ['_']
extend-ignore = ['E4', 'E74', 'E722']
extend-select = ['ARG', 'Q']
#tab_size = 4

[tool.ruff.flake8-quotes]
inline-quotes = 'single'
docstring-quotes = 'single'
multiline-quotes = 'single'

```

**Python 3.10.6** on **VSCodium 1.80.2.23209** (distro repo, not Flatpak) on **Pop!_OS 22.04 LTS**.

**Comment by zehkira** [comment]
I added the `extend-exclude`, and instead of fixing the issue that somehow made it worse:

![Linting Python itself?](https://github.com/astral-sh/ruff-vscode/assets/111002801/e60b6f0a-c296-4ec5-9944-64690184d7b7)

```toml
[tool.ruff]
builtins = ['_']
extend-ignore = ['E4', 'E74', 'E722']
extend-select = ['ARG', 'Q']
extend-exclude = ['.vscode-oss']
#tab_size = 4

[tool.ruff.flake8-quotes]
inline-quotes = 'single'
docstring-quotes = 'single'
multiline-quotes = 'single'
```
