### ISSUE TITLE
Ruff doesn't automatically format Python code when the file is saved

### ISSUE THREAD

**Issue by xshapira** [astral-sh/ruff-vscode#312]
![CleanShot 2023-10-25 at 12 13 58](https://github.com/astral-sh/ruff-vscode/assets/48856190/dc8ae132-b25e-4307-82a3-923bc3b277cd)

I'm sharing my VS Code's `settings.json`:
```json
{
  "[python]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "charliermarsh.ruff",
    "editor.formatOnPaste": false,
    "editor.formatOnType": true,
    "editor.tabSize": 4,
	"editor.insertSpaces": true, // This one forces the tab to be **space**
    "editor.codeActionsOnSave": {
      "source.fixAll.ruff": true
    }
  }
}

```

And also `pyproject.toml`:
```toml
[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Admin <admin@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"
faker = "^19.6.2"
icecream = "^2.1.3"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.2"
mypy = "^1.6.0"
pre-commit = "^3.5.0"
types-requests = "^2.31.0.9"

[tool.mypy]
follow_imports = "silent"
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
no_implicit_reexport = true
check_untyped_defs = true
strict_equality = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
show_error_codes = true

[tool.ruff]
line-length = 88
exclude = [
    '.git',
    '__pycache__',
    '__init__.py',
    '.mypy_cache',
    '.pytest_cache',
]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # line too long
    "C901",  # Comprehension is too complex (11 > 10)
    "W191", # indentation contains tabs
]
unfixable = ["F841"]

[tool.ruff.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```
