### ISSUE TITLE
Organize imports on save with custom config file location

### ISSUE THREAD

**Issue by toinbis** [astral-sh/ruff-vscode#411]
I have issues with import formats on save not respect the ruff config file.

```
    "ruff.lint.args": [
        "--config=${workspaceFolder}/src/shared_core/static_configs/ruff.toml",
        "check",
        "--unsafe-fixes",
        "--fix"
    ],


    "ruff.format.args": [
        "--config=${workspaceFolder}/src/shared_core/static_configs/ruff.toml",
        "--preview"
    ],

    
    "[python]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
          "source.fixAll": "always",
          "source.organizeImports": "always"
        },
        "editor.defaultFormatter": "charliermarsh.ruff"
      },
```

This is my vscode settings.json. I get consistent behaviour (=reading and using custom config file location) for:
- ruff.lint.args & ruff format.args; VSCode highlights errors based on the config file;
- The suggested fix dropdown:
![Screenshot 2024-02-20 at 14 41 12](https://github.com/astral-sh/ruff-vscode/assets/68685/02ff9189-73f2-4aa9-a67b-135c1f8967c3)
It also fixes according to my config file.
- The same command run from CLI also behaves identically.

I.e. All as expected!

Until I want to do organize imports automatically on save. So these settings come into effect: 

```
"[python]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
          "source.fixAll": "always",
          "source.organizeImports": "always"
        },
        "editor.defaultFormatter": "charliermarsh.ruff"
      }
```
 And they seem to just use default ruff without any custom config. And it just formats differentely!
 
 `"ruff.lint.run": "onType|onSave",` seemed like a setting which could help, but this settings, as shown by VSCode, is invalid.
 
 How do I sort imports on save when using custom ruff config file location?
 
 Thanks

**Comment by dhruvmanila** [comment]
Thank you for opening the issue! Can you provide the content in your config file? And can you expand on how "it formats differently"? Like, what is the expected behavior and what are you actually getting?

**Comment by chrisk314** [comment]
Hi, I'm having the same problem. It just started happening recently, not sure exactly when... Essentially the result of auto-formatting from VS Code is different to the result of running `ruff check --fix` on the CLI. From the ruff server logs I can see the packaged ruff version is 0.5.4. The version I have installed in my venv is 0.5.6. I have tried downgrading the version in my venv to 0.5.4 and the results are the same.

Here is my vscode settings file from the project folder.
```javascript
{
    "python.defaultInterpreterPath": ".venv/bin/python",
    "python.envFile": "${workspaceFolder}/.env",
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
    "python.testing.autoTestDiscoverOnSaveEnabled": true,
    "python.testing.pytestArgs": [
        "-rs", "tests/"
    ],
    "editor.formatOnSave": false,
    "[python]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.codeActionsOnSave": {
            "source.organizeImports": "explicit",
            "source.fixAll": "explicit"
        }
    },
    "mypy.configFile": "pyproject.toml",
    "mypy.targets": ["./tunedd_api", "./tests"],
    "mypy.runUsingActiveInterpreter": true,
}
```

And here are the ruff related settings from my pyproject file, which is at the root of my project folder.
```toml
[tool.ruff]  # Code formatting and linting
line-length = 100
src = ["tunedd_api", "tests"]
extend-exclude = ["__pycache__"]
output-format = "grouped"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = ["D", "E", "F", "I", "W"]
ignore = ["D105", "D107", "D401", "E203", "E226", "E24", "E731", "E741", "F541", "F821", "W605"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["tunedd_api"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
no-lines-before = ["local-folder"]
force-sort-within-sections = true
combine-as-imports = true
split-on-trailing-comma = true
relative-imports-order = "furthest-to-closest"
lines-after-imports = 2
``` 

Here is an illustrative example of how the VS Code extension sorts the files on save. This appears to be consistent with the [documentation for `from-first`](https://docs.astral.sh/ruff/settings/#lint_isort_from-first) which states that the default behaviour is to put from imports after regular imports. 
![image](https://github.com/user-attachments/assets/be299475-e348-4468-bb1e-3dd7ce859acc)

Now here is how it looks after running `ruff check --fix` on the CLI. This appears to be sorting the imports alphabetically without consideration of whether the import statement is a regular import or a from import. It is not apparent to me from the documentation that such ordering is a configurable possibility.
![image](https://github.com/user-attachments/assets/0c756642-faae-4ba5-9a1a-731431f2d55b)
