### ISSUE TITLE
Ruff Native Server spams `Ruff encountered a problem. Check the logs for more details.` with bad symbols.

### ISSUE THREAD

**Issue by theelderbeever** [astral-sh/ruff-vscode#482]
This might not be an actual bug however, it is somewhat annoying.... If you use the new native lsp in `ruff` with vscode and have a bad symbol in your file and save you will get an error pop up in the lower right corner of VSCode for the extension. 

<img width="463" alt="image" src="https://github.com/astral-sh/ruff-vscode/assets/29295582/6c31d124-e737-4869-8cfe-2582957f6d8c">

A simple test
```python
# hello.py
print(some_var) # some_var hasn't been set yet.
```

Now save the file. Every save triggers the pop up.

While it isn't technically wrong that there is an error its a little overkill to be told to check the extension logs for the error when the typical red underline sufficiently captures the code error.

**Comment by MichaReiser** [comment]
Can you tell us a bit more about your setup? What version of the extension and ruff are you using? Do you use the new experimental lsp backend?

**Comment by theelderbeever** [comment]
@MichaReiser Yeah sorry about the lack of details. Its the new experimental backend on v0.4.5.

Pertinent settings in VSCode
```json
{
    "ruff.nativeServer": true
    "notebook.formatOnSave.enabled": true,
    "ruff.lint.args": ["--config=./pyproject.toml"],
    "notebook.codeActionsOnSave": {
        "notebook.source.fixAll": false,
        "notebook.source.organizeImports": "explicit"
      },
    "[python]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.codeActionsOnSave": {
          "source.fixAll": "never",
          "source.organizeImports": "never"
        }
    },
}
```

`pyproject.toml`
```toml

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E4", "E7", "E9", "F"]
ignore = ["E402"]

ignore-init-module-imports = true

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
```
