### ISSUE TITLE
Lint:Ignore doesn't work

### ISSUE THREAD

**Issue by Filyus** [astral-sh/ruff-vscode#494]
VS Code Settings:
```json
{
  "ruff.lint.ignore": [
    "E402"
  ]
}
```

The `ignore` parameter is not added to `\extensions\charliermarsh.ruff-2024.26.0-win32-x64\pyproject.toml`:
```toml
[tool.ruff.lint]
select = ["E", "F", "W", "Q", "UP", "I", "N"]
```

Ruff v2024.26.0

VS Code:
```
Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045
```

With a **native server** enabled everything is fine.
