### ISSUE TITLE
Misconfigured Python interpreter leads to Ruff extension not loading

### ISSUE THREAD

**Issue by chrisk314** [astral-sh/ruff-vscode#619]
Recently Ruff stopped performing any code actions for my python files and the extension state icon remains spinning indefinitely (see screenshot below). This issue is similar to #609 in appearance in the VS Code UI, but different in that there appears to be no communication with the ruff server.
![image](https://github.com/user-attachments/assets/880b1a0b-9336-4f50-927a-910505f1a3e1)

This started happening a couple of weeks ago without any changes to my vs code settings. I'm on auto update, so I guess an update caused this. I've tried with `ruff.nativeServer` set to `on`, `off`, and `auto`. This is all I get in the ruff logs (verbose logging enabled). Seeing this with all my environments. I've tried uninstalling the extension and reinstalling.
```txt
2024-09-19 20:57:24.113 [info] Name: Ruff
2024-09-19 20:57:24.113 [info] Module: ruff
2024-09-19 20:57:24.113 [info] Python extension loading
2024-09-19 20:57:24.113 [info] Waiting for interpreter from python extension.
2024-09-19 20:57:24.574 [info] Python extension loaded
2024-09-19 20:57:24.900 [info] Using interpreter: /home/csk/.pyenv/versions/plugboard-3.12/bin/python
```
User VS Code settings file Ruff config
```json
{
    "ruff.nativeServer": "auto",
    "ruff.trace.server": "verbose",
}
```

Project VS Code settings file (`.vscode/settings.json`)
```json
{
    "python.defaultInterpreterPath": "/home/csk/.pyenv/versions/plugboard-3.12/bin/python3.12",
    "python.envFile": "${workspaceFolder}/.env",
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
    "python.testing.autoTestDiscoverOnSaveEnabled": true,
    "python.testing.pytestArgs": [
        "-rs", "tests/"
    ],
    "editor.formatOnSave": false,
    "[python]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.codeActionsOnSave": {
            "source.organizeImports": "explicit",
            "source.fixAll": "explicit"
        }
    },
    "mypy.configFile": "pyproject.toml",
    "mypy.targets": ["./plugboard", "./tests"],
    "mypy.runUsingActiveInterpreter": true,
}
```

Pyproject Ruff settings (`pyproject.toml`)
```toml
[tool.ruff]  # Code formatting and linting
line-length = 100
src = ["plugboard", "tests"]
extend-exclude = ["__pycache__"]
output-format = "grouped"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = ["D", "E", "F", "I", "W"]
ignore = ["D105", "D107", "D401", "E203", "E226", "E24", "E731", "E741", "F541", "F821", "W605"]
exclude = ["docs/*"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["plugboard"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
no-lines-before = ["local-folder"]
force-sort-within-sections = true
combine-as-imports = true
split-on-trailing-comma = true
relative-imports-order = "furthest-to-closest"
lines-after-imports = 2
```

My env:
- VS Code v1.94.0 Insider
- Ruff VS Code extension v2024.48.0
- Windows 11
- WSL2 with Ubuntu 24.04
- Python 3.12.6 installed in pyenv
- Python virtualenv installed with pyenv-virtualenv
- Ruff v0.5.7 installed in venv (working correctly on CLI)

This problem is not limited to pyenv virtualenvs. I'm having the same issue with all VS Code projects some of which use virtualenvs created with the system python using `python -m venv .venv` etc.
