### ISSUE TITLE
Suboptimal order of Quick Fix actions when trying to import

### ISSUE THREAD

**Issue by StasDeep** [astral-sh/ruff-vscode#624]
When I am trying to import a missing module, I press Opt+Enter to see the actions and with Ruff the most-used action in this situation ("Add import") is moved below the barely ever used "Disable for this line".

![CleanShot 2024-10-03 at 10 53 41@2x](https://github.com/user-attachments/assets/39e21a00-a83b-4366-a3da-456f90027194)

Is this misconfiguration on my side or is this sort of a bug?

**IDE**: Cursor v0.41.3

**Ruff extension version**: v2024.50.0

**`pyproject.toml`**:
```toml
[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
extend-select = [
    "I",  # sort imports
    "PLE",  # pylint errors
    "FIX",  # FIXME comments
]
```
